theme = "rose_pine_dawn"

[editor]
auto-format = true
line-number = "relative"
workspace-lsp-roots = [".git"]

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[keys.normal]
Y = "yank_joined"
