[language-server.lemminx]
command = "lemminx-linux"

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true}
rope_autoimport = {enabled = true}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = {enabled = false}

[[language]]
name = "xml"
language-servers = ["lemminx"]
file-types = ["xml", { glob = "SFPA*" }]
auto-format = true
